const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  NOT_FOUND: 'NOT_FOUND',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  EVIDENCE_TIME_TOO_EARLY: 'EVIDENCE_TIME_TOO_EARLY',
  DUPLICATE_EVIDENCE_HASH: 'DUPLICATE_EVIDENCE_HASH',
  INCIDENT_CLOSED: 'INCIDENT_CLOSED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  EXPORT_CONFLICT: 'EXPORT_CONFLICT',
  EXPORT_FAILED: 'EXPORT_FAILED',
  IMPORT_VALIDATION_ERROR: 'IMPORT_VALIDATION_ERROR',
  IMPORT_CONFLICT: 'IMPORT_CONFLICT',
  IMPORT_FAILED: 'IMPORT_FAILED',
  RECEIPT_INCIDENT_NOT_CLOSED: 'RECEIPT_INCIDENT_NOT_CLOSED',
  RECEIPT_NO_EVIDENCE: 'RECEIPT_NO_EVIDENCE',
  RECEIPT_EXPIRED: 'RECEIPT_EXPIRED',
  RECEIPT_DUPLICATE: 'RECEIPT_DUPLICATE',
  RECEIPT_INVALID_CODE: 'RECEIPT_INVALID_CODE',
  RECEIPT_ALREADY_SIGNED: 'RECEIPT_ALREADY_SIGNED',
  RECEIPT_REVOKED: 'RECEIPT_REVOKED',
  RECEIPT_CONFLICT: 'RECEIPT_CONFLICT',
  RECEIPT_NOT_FOUND: 'RECEIPT_NOT_FOUND',
  RECEIPT_CREATE_FAILED: 'RECEIPT_CREATE_FAILED',
  RECEIPT_SIGN_FAILED: 'RECEIPT_SIGN_FAILED',
  RECEIPT_REVOKE_FAILED: 'RECEIPT_REVOKE_FAILED',
  SHIFT_HANDOVER_NOT_FOUND: 'SHIFT_HANDOVER_NOT_FOUND',
  SHIFT_HANDOVER_CREATE_FAILED: 'SHIFT_HANDOVER_CREATE_FAILED',
  SHIFT_HANDOVER_ALREADY_CONFIRMED: 'SHIFT_HANDOVER_ALREADY_CONFIRMED',
  SHIFT_HANDOVER_ALREADY_REVOKED: 'SHIFT_HANDOVER_ALREADY_REVOKED',
  SHIFT_HANDOVER_CONFIRM_FAILED: 'SHIFT_HANDOVER_CONFIRM_FAILED',
  SHIFT_HANDOVER_REVOKE_FAILED: 'SHIFT_HANDOVER_REVOKE_FAILED',
  SHIFT_HANDOVER_CONFLICT: 'SHIFT_HANDOVER_CONFLICT',
  SHIFT_HANDOVER_NOT_CREATOR: 'SHIFT_HANDOVER_NOT_CREATOR',
  SHIFT_HANDOVER_INVALID_INCIDENT: 'SHIFT_HANDOVER_INVALID_INCIDENT'
};

const ERROR_MESSAGES = {
  [ERROR_CODES.VALIDATION_ERROR]: '请求参数验证失败',
  [ERROR_CODES.PERMISSION_DENIED]: '权限不足，无法执行该操作',
  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.INVALID_STATUS_TRANSITION]: '无效的状态流转',
  [ERROR_CODES.EVIDENCE_TIME_TOO_EARLY]: '证据采集时间早于事故发生时间',
  [ERROR_CODES.DUPLICATE_EVIDENCE_HASH]: '同一事故下已存在相同哈希的证据',
  [ERROR_CODES.INCIDENT_CLOSED]: '事故已结案，无法新增证据，如需补充请先申请重新打开',
  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
  [ERROR_CODES.UNAUTHORIZED]: '未授权访问，请提供有效的用户信息',
  [ERROR_CODES.EXPORT_CONFLICT]: '导出文件名已存在，未覆盖',
  [ERROR_CODES.EXPORT_FAILED]: '导出操作失败',
  [ERROR_CODES.IMPORT_VALIDATION_ERROR]: '归档校验失败',
  [ERROR_CODES.IMPORT_CONFLICT]: '导入冲突：事故ID已存在',
  [ERROR_CODES.IMPORT_FAILED]: '导入操作失败',
  [ERROR_CODES.RECEIPT_INCIDENT_NOT_CLOSED]: '事故未结案，无法生成签收包',
  [ERROR_CODES.RECEIPT_NO_EVIDENCE]: '事故证据为空，无法生成签收包',
  [ERROR_CODES.RECEIPT_EXPIRED]: '签收包已过期',
  [ERROR_CODES.RECEIPT_DUPLICATE]: '重复签收',
  [ERROR_CODES.RECEIPT_INVALID_CODE]: '签收码无效',
  [ERROR_CODES.RECEIPT_ALREADY_SIGNED]: '签收包已完成签收',
  [ERROR_CODES.RECEIPT_REVOKED]: '签收包已被撤销',
  [ERROR_CODES.RECEIPT_CONFLICT]: '该事故已存在未完成的签收包',
  [ERROR_CODES.RECEIPT_NOT_FOUND]: '签收包不存在',
  [ERROR_CODES.RECEIPT_CREATE_FAILED]: '签收包创建失败',
  [ERROR_CODES.RECEIPT_SIGN_FAILED]: '签收失败',
  [ERROR_CODES.RECEIPT_REVOKE_FAILED]: '签收包撤销失败',
  [ERROR_CODES.SHIFT_HANDOVER_NOT_FOUND]: '交接班不存在',
  [ERROR_CODES.SHIFT_HANDOVER_CREATE_FAILED]: '交接班创建失败',
  [ERROR_CODES.SHIFT_HANDOVER_ALREADY_CONFIRMED]: '交接班已被确认，无法执行该操作',
  [ERROR_CODES.SHIFT_HANDOVER_ALREADY_REVOKED]: '交接班已被撤回，无法执行该操作',
  [ERROR_CODES.SHIFT_HANDOVER_CONFIRM_FAILED]: '交接班确认失败',
  [ERROR_CODES.SHIFT_HANDOVER_REVOKE_FAILED]: '交接班撤回失败',
  [ERROR_CODES.SHIFT_HANDOVER_CONFLICT]: '交接班状态冲突',
  [ERROR_CODES.SHIFT_HANDOVER_NOT_CREATOR]: '仅交班人可撤回交接班',
  [ERROR_CODES.SHIFT_HANDOVER_INVALID_INCIDENT]: '关联的事故不存在'
};

function createErrorResponse(code, details = null) {
  const response = {
    success: false,
    error: {
      code,
      message: ERROR_MESSAGES[code] || '未知错误'
    }
  };
  if (details) {
    response.error.details = details;
  }
  return response;
}

module.exports = {
  ERROR_CODES,
  ERROR_MESSAGES,
  createErrorResponse
};
