const INCIDENT_STATUS = {
  REPORTED: 'reported',
  EVIDENCE_COLLECTING: 'evidence_collecting',
  FOREMAN_REVIEWED: 'foreman_reviewed',
  SECURITY_CONFIRMED: 'security_confirmed',
  CLOSED: 'closed',
  RETURNED: 'returned'
};

const INCIDENT_STATUS_FLOW = {
  [INCIDENT_STATUS.REPORTED]: [INCIDENT_STATUS.EVIDENCE_COLLECTING, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.EVIDENCE_COLLECTING]: [INCIDENT_STATUS.FOREMAN_REVIEWED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.FOREMAN_REVIEWED]: [INCIDENT_STATUS.SECURITY_CONFIRMED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.SECURITY_CONFIRMED]: [INCIDENT_STATUS.CLOSED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.RETURNED]: [INCIDENT_STATUS.EVIDENCE_COLLECTING]
};

const INCIDENT_LEVEL = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

const USER_ROLE = {
  REPORTER: 'reporter',
  FOREMAN: 'foreman',
  SECURITY: 'security',
  ADMIN: 'admin'
};

const PERMISSIONS = {
  CREATE_INCIDENT: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  ADD_EVIDENCE: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  FOREMAN_REVIEW: [USER_ROLE.FOREMAN, USER_ROLE.ADMIN],
  SECURITY_CONFIRM: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  CLOSE_INCIDENT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  RETURN_INCIDENT: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  REOPEN_INCIDENT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  EXPORT_DATA: [USER_ROLE.ADMIN, USER_ROLE.SECURITY],
  IMPORT_DATA: [USER_ROLE.ADMIN, USER_ROLE.SECURITY]
};

const AUDIT_ACTION = {
  INCIDENT_CREATED: 'incident_created',
  INCIDENT_STATUS_CHANGED: 'incident_status_changed',
  EVIDENCE_ADDED: 'evidence_added',
  DATA_EXPORTED: 'data_exported',
  DATA_EXPORT_FAILED: 'data_export_failed',
  EXPORT_CONFIG_UPDATED: 'export_config_updated',
  DATA_IMPORTED: 'data_imported',
  DATA_IMPORT_FAILED: 'data_import_failed',
  DATA_IMPORT_VALIDATION_FAILED: 'data_import_validation_failed'
};

module.exports = {
  INCIDENT_STATUS,
  INCIDENT_STATUS_FLOW,
  INCIDENT_LEVEL,
  USER_ROLE,
  PERMISSIONS,
  AUDIT_ACTION
};
