const INCIDENT_STATUS = {
  REPORTED: 'reported',
  EVIDENCE_COLLECTING: 'evidence_collecting',
  FOREMAN_REVIEWED: 'foreman_reviewed',
  SECURITY_CONFIRMED: 'security_confirmed',
  CLOSED: 'closed',
  RETURNED: 'returned'
};

const INCIDENT_STATUS_FLOW = {
  [INCIDENT_STATUS.REPORTED]: [INCIDENT_STATUS.EVIDENCE_COLLECTING, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.EVIDENCE_COLLECTING]: [INCIDENT_STATUS.FOREMAN_REVIEWED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.FOREMAN_REVIEWED]: [INCIDENT_STATUS.SECURITY_CONFIRMED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.SECURITY_CONFIRMED]: [INCIDENT_STATUS.CLOSED, INCIDENT_STATUS.RETURNED],
  [INCIDENT_STATUS.RETURNED]: [INCIDENT_STATUS.EVIDENCE_COLLECTING]
};

const INCIDENT_LEVEL = {
  LOW: 'low',
  MEDIUM: 'medium',
  HIGH: 'high',
  CRITICAL: 'critical'
};

const USER_ROLE = {
  REPORTER: 'reporter',
  FOREMAN: 'foreman',
  SECURITY: 'security',
  ADMIN: 'admin'
};

const RECEIPT_PACKAGE_STATUS = {
  PENDING: 'pending',
  SIGNED: 'signed',
  REVOKED: 'revoked',
  EXPIRED: 'expired'
};

const RECEIPT_CONFLICT_STRATEGY = {
  ERROR: 'error',
  SUPERSEDE: 'supersede'
};

const BORROW_REQUEST_STATUS = {
  PENDING: 'pending',
  APPROVED: 'approved',
  REJECTED: 'rejected',
  REVOKED: 'revoked',
  EXPIRED: 'expired'
};

const BORROW_CREDENTIAL_STATUS = {
  ACTIVE: 'active',
  USED: 'used',
  REVOKED: 'revoked',
  EXPIRED: 'expired',
  INVALID: 'invalid'
};

const SHIFT_HANDOVER_STATUS = {
  PENDING: 'pending',
  CONFIRMED: 'confirmed',
  REVOKED: 'revoked'
};

const PERMISSIONS = {
  CREATE_INCIDENT: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  ADD_EVIDENCE: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  FOREMAN_REVIEW: [USER_ROLE.FOREMAN, USER_ROLE.ADMIN],
  SECURITY_CONFIRM: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  CLOSE_INCIDENT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  RETURN_INCIDENT: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  REOPEN_INCIDENT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  EXPORT_DATA: [USER_ROLE.ADMIN, USER_ROLE.SECURITY],
  IMPORT_DATA: [USER_ROLE.ADMIN, USER_ROLE.SECURITY],
  CREATE_RECEIPT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  REVOKE_RECEIPT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  VIEW_RECEIPT: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  CREATE_BORROW_REQUEST: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  APPROVE_BORROW_REQUEST: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  VIEW_ALL_BORROW_REQUESTS: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  REVOKE_BORROW_CREDENTIAL: [USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  DOWNLOAD_BORROW_EVIDENCE: [USER_ROLE.REPORTER, USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  VIEW_ALL_INCIDENTS: [USER_ROLE.ADMIN, USER_ROLE.SECURITY],
  MANAGE_OVERDUE_CONFIG: [USER_ROLE.ADMIN],
  CREATE_SHIFT_HANDOVER: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  CONFIRM_SHIFT_HANDOVER: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN],
  VIEW_SHIFT_HANDOVER: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN, USER_ROLE.REPORTER],
  REVOKE_SHIFT_HANDOVER: [USER_ROLE.FOREMAN, USER_ROLE.SECURITY, USER_ROLE.ADMIN]
};

const SORT_FIELDS = {
  CREATED_AT: 'createdAt',
  UPDATED_AT: 'updatedAt',
  LEVEL: 'level'
};

const SORT_DIRECTIONS = {
  ASC: 'asc',
  DESC: 'desc'
};

const LEVEL_ORDER = {
  [INCIDENT_LEVEL.LOW]: 1,
  [INCIDENT_LEVEL.MEDIUM]: 2,
  [INCIDENT_LEVEL.HIGH]: 3,
  [INCIDENT_LEVEL.CRITICAL]: 4
};

const AUDIT_ACTION = {
  INCIDENT_CREATED: 'incident_created',
  INCIDENT_STATUS_CHANGED: 'incident_status_changed',
  EVIDENCE_ADDED: 'evidence_added',
  DATA_EXPORTED: 'data_exported',
  DATA_EXPORT_FAILED: 'data_export_failed',
  EXPORT_CONFIG_UPDATED: 'export_config_updated',
  DATA_IMPORTED: 'data_imported',
  DATA_IMPORT_FAILED: 'data_import_failed',
  DATA_IMPORT_VALIDATION_FAILED: 'data_import_validation_failed',
  RECEIPT_CREATED: 'receipt_created',
  RECEIPT_CREATE_FAILED: 'receipt_create_failed',
  RECEIPT_SIGNED: 'receipt_signed',
  RECEIPT_SIGN_FAILED: 'receipt_sign_failed',
  RECEIPT_REVOKED: 'receipt_revoked',
  RECEIPT_REVOKE_FAILED: 'receipt_revoke_failed',
  RECEIPT_VIEWED: 'receipt_viewed',
  BORROW_REQUEST_CREATED: 'borrow_request_created',
  BORROW_REQUEST_CREATE_FAILED: 'borrow_request_create_failed',
  BORROW_REQUEST_APPROVED: 'borrow_request_approved',
  BORROW_REQUEST_APPROVE_FAILED: 'borrow_request_approve_failed',
  BORROW_REQUEST_REJECTED: 'borrow_request_rejected',
  BORROW_REQUEST_REJECT_FAILED: 'borrow_request_reject_failed',
  BORROW_REQUEST_VIEWED: 'borrow_request_viewed',
  BORROW_CREDENTIAL_CREATED: 'borrow_credential_created',
  BORROW_CREDENTIAL_USED: 'borrow_credential_used',
  BORROW_CREDENTIAL_USE_FAILED: 'borrow_credential_use_failed',
  BORROW_CREDENTIAL_REVOKED: 'borrow_credential_revoked',
  BORROW_CREDENTIAL_REVOKE_FAILED: 'borrow_credential_revoke_failed',
  BORROW_EVIDENCE_DOWNLOADED: 'borrow_evidence_downloaded',
  BORROW_EVIDENCE_DOWNLOAD_FAILED: 'borrow_evidence_download_failed',
  OVERDUE_CONFIG_UPDATED: 'overdue_config_updated',
  SHIFT_HANDOVER_CREATED: 'shift_handover_created',
  SHIFT_HANDOVER_CREATE_FAILED: 'shift_handover_create_failed',
  SHIFT_HANDOVER_CONFIRMED: 'shift_handover_confirmed',
  SHIFT_HANDOVER_CONFIRM_FAILED: 'shift_handover_confirm_failed',
  SHIFT_HANDOVER_REVOKED: 'shift_handover_revoked',
  SHIFT_HANDOVER_REVOKE_FAILED: 'shift_handover_revoke_failed',
  SHIFT_HANDOVER_VIEWED: 'shift_handover_viewed'
};

module.exports = {
  INCIDENT_STATUS,
  INCIDENT_STATUS_FLOW,
  INCIDENT_LEVEL,
  USER_ROLE,
  PERMISSIONS,
  AUDIT_ACTION,
  RECEIPT_PACKAGE_STATUS,
  RECEIPT_CONFLICT_STRATEGY,
  BORROW_REQUEST_STATUS,
  BORROW_CREDENTIAL_STATUS,
  SHIFT_HANDOVER_STATUS,
  SORT_FIELDS,
  SORT_DIRECTIONS,
  LEVEL_ORDER
};
